export const STATION_CODES = {
    // Major Cities
    'NDLS': 'New Delhi',
    'HWH': 'Howrah Junction',
    'CSMT': 'Mumbai CST',
    'MMCT': 'Mumbai Central',
    'MAS': 'Chennai Central',
    'SBC': 'Bangalore City',
    'HYB': 'Hyderabad',
    'PUNE': 'Pune Junction',
    'ADI': 'Ahmedabad Junction',
    'JP': 'Jaipur',
    'LKO': 'Lucknow',
    'CNB': 'Kanpur Central',
    'PNBE': 'Patna Junction',
    'GHY': 'Guwahati',
    'BBS': 'Bhubaneswar',
    'VSKP': 'Visakhapatnam',
    'TVC': 'Trivandrum Central',
    'ERS': 'Ernakulam Junction',
    'CBE': 'Coimbatore Junction',
    'MDU': 'Madurai Junction',
    'TPJ': 'Tiruchirapalli',
    'SA': 'Salem Junction',
    'KPD': 'Katpadi Junction',
    'JTJ': 'Jolarpettai Junction',
    'BZA': 'Vijayawada Junction',
    'SC': 'Secunderabad Junction',
    'KCG': 'Kacheguda',
    'GTL': 'Guntakal Junction',
    'UBL': 'Hubli Junction',
    'DWR': 'Dharwad',
    'MAJN': 'Mangalore Junction',
    'CAN': 'Kannur',
    'CLT': 'Kozhikode',
    'TCR': 'Thrissur',
    'AWY': 'Aluva',
    'KTYM': 'Kottayam',
    'QLN': 'Kollam Junction',
    'CAPE': 'Kanyakumari',
    
    // North India
    'AMR': 'Amritsar Junction',
    'JUC': 'Jalandhar City',
    'LDH': 'Ludhiana Junction',
    'CDG': 'Chandigarh',
    'UMB': 'Ambala Cantt',
    'KUR': 'Kurukshetra Junction',
    'PNP': 'Panipat Junction',
    'ROK': 'Rohtak Junction',
    'RE': 'Rewari Junction',
    'GGN': 'Gurgaon',
    'FDB': 'Faridabad',
    'MTJ': 'Mathura Junction',
    'AGC': 'Agra Cantt',
    'GWL': 'Gwalior Junction',
    'JHS': 'Jhansi Junction',
    'BINA': 'Bina Junction',
    'BPL': 'Bhopal Junction',
    'HBJ': 'Habibganj',
    'JBP': 'Jabalpur',
    'KTE': 'Katni',
    'STA': 'Satna',
    'MKP': 'Manikpur Junction',
    'COI': 'Chheoki',
    'PRYJ': 'Prayagraj Junction',
    'BSB': 'Varanasi Junction',
    'MGS': 'Mughal Sarai Junction',
    'DDU': 'Pt. Deen Dayal Upadhyaya Junction',
    'GKP': 'Gorakhpur Junction',
    'CPR': 'Chhapra Junction',
    'SEE': 'Sonpur Junction',
    'HJP': 'Hajipur Junction',
    'MFP': 'Muzaffarpur Junction',
    'DBG': 'Darbhanga Junction',
    'SPJ': 'Samastipur Junction',
    'BJU': 'Barauni Junction',
    'KIUL': 'Kiul Junction',
    'JAJ': 'Jhajha',
    'JSME': 'Jasidih Junction',
    'MDP': 'Madhupur Junction',
    'CRJ': 'Chittaranjan',
    'ASN': 'Asansol Junction',
    'DGR': 'Durgapur',
    'BWN': 'Barddhaman Junction',
    
    // East India
    'KOAA': 'Kolkata',
    'SDAH': 'Sealdah',
    'SHM': 'Shalimar',
    'BDC': 'Bandel Junction',
    'NH': 'Naihati Junction',
    'RHA': 'Ranaghat Junction',
    'KNJ': 'Krishnanagar City Junction',
    'MLDT': 'Malda Town',
    'NJP': 'New Jalpaiguri',
    'KIR': 'Katihar Junction',
    'BOE': 'Barsoi Junction',
    'KNE': 'Kishanganj',
    'NNA': 'Naugachia',
    'THB': 'Thana Bihpur Junction',
    'BGS': 'Begu Sarai',
    'KGG': 'Khagaria Junction',
    'MNE': 'Mansi Junction',
    'SBV': 'Simri Bakhtiarpur',
    'DSS': 'Dalsingh Sarai',
    'SPP': 'Shahpur Patori',
    'LSI': 'Laheria Sarai',
    'DGA': 'Dighwara',
    'PPU': 'Pipariya',
    'BUJ': 'Barauni Junction',
    
    // West India
    'ST': 'Surat',
    'BRC': 'Vadodara Junction',
    'AKV': 'Ankleshwar Junction',
    'BH': 'Bharuch Junction',
    'KIM': 'Kim',
    'VAPI': 'Vapi',
    'BVI': 'Borivali',
    'ADH': 'Andheri',
    'BA': 'Bandra',
    'DDR': 'Dadar',
    'KYN': 'Kalyan Junction',
    'IGP': 'Igatpuri',
    'NK': 'Nashik Road',
    'MMR': 'Manmad Junction',
    'AWB': 'Aurangabad',
    'J': 'Jalna',
    'PBN': 'Parbhani Junction',
    'NED': 'Nanded',
    'MUE': 'Mudkhed Junction',
    'NZB': 'Nizamabad Junction',
    'KMC': 'Kamareddy',
    'MED': 'Medchal',
    'BMT': 'Begumpet',
    'LPI': 'Lingampalli',
    'VKB': 'Vikarabad Junction',
    'ZB': 'Zahirabad Junction',
    'SDB': 'Shahabad',
    'GR': 'Gulbarga',
    'WADI': 'Wadi Junction',
    'RC': 'Raichur Junction',
    'MALM': 'Mantralayam Road',
    'AD': 'Adoni',
    'GTL': 'Guntakal Junction',
    'ATP': 'Anantapur',
    'DMM': 'Dharmavaram Junction',
    'HUP': 'Hindupur',
    'YPR': 'Yesvantpur Junction',
    'KJM': 'Krishnarajapuram',
    'BWT': 'Bangarapet Junction',
    'JTJ': 'Jolarpettai Junction',
    'SA': 'Salem Junction',
    'ED': 'Erode Junction',
    'TUP': 'Tirupur',
    'CBE': 'Coimbatore Junction',
    'PGT': 'Palakkad Junction',
    'SRR': 'Shoranur Junction',
    'TCR': 'Thrissur',
    'AWY': 'Aluva',
    'ERS': 'Ernakulam Junction',
    'KTYM': 'Kottayam',
    'CNGR': 'Chengannur',
    'TRVL': 'Tiruvalla',
    'QLN': 'Kollam Junction',
    'VAK': 'Varkala Sivagiri',
    'TVC': 'Trivandrum Central',
    'CAPE': 'Kanyakumari',
    
    // Central India
    'NGP': 'Nagpur',
    'AJNI': 'Ajni',
    'WR': 'Wardha Junction',
    'CD': 'Chandrapur',
    'BPQ': 'Balharshah',
    'SKZR': 'Sirpur Kagaznagar',
    'BPA': 'Bellampalli',
    'RDM': 'Ramgundam',
    'PDPL': 'Peddapalli',
    'KZJ': 'Kazipet Junction',
    'WL': 'Warangal',
    'MABD': 'Mahbubabad',
    'DKJ': 'Dornakal Junction',
    'KMT': 'Khammam',
    'BZA': 'Vijayawada Junction',
    'TEL': 'Tenali Junction',
    'OGL': 'Ongole',
    'NLR': 'Nellore',
    'GDR': 'Gudur Junction',
    'RU': 'Renigunta Junction',
    'TPTY': 'Tirupati',
    'CTO': 'Chittoor',
    'JTJ': 'Jolarpettai Junction',
    'BWT': 'Bangarapet Junction',
    'KJM': 'Krishnarajapuram',
    'YPR': 'Yesvantpur Junction',
    'TK': 'Tumkur',
    'ASK': 'Arsikere Junction',
    'RRB': 'Birur Junction',
    'DVG': 'Davangere',
    'HRR': 'Harihar',
    'RNR': 'Ranibennur',
    'HVR': 'Haveri',
    'UBL': 'Hubli Junction',
    'DWR': 'Dharwad',
    'LWR': 'Londa Junction',
    'CLR': 'Castle Rock',
    'QLM': 'Kulem',
    'MAO': 'Madgaon Junction',
    'KRMI': 'Karmali',
    'THVM': 'Thivim',
    'PERN': 'Pernem',
    'SWV': 'Sawantwadi Road',
    'RN': 'Ratnagiri',
    'CHI': 'Chiplun',
    'KHED': 'Khed',
    'ROHA': 'Roha',
    'PEN': 'Pen',
    'PNVL': 'Panvel',
    'TNA': 'Thane',
    'KYN': 'Kalyan Junction'
};

export const searchStations = (query) => {
    if (!query || query.length < 2) return [];
    
    const searchTerm = query.toLowerCase();
    const results = [];
    
    // Search by station code
    Object.entries(STATION_CODES).forEach(([code, name]) => {
        if (code.toLowerCase().includes(searchTerm)) {
            results.push({ code, name, type: 'code' });
        }
    });
    
    // Search by station name
    Object.entries(STATION_CODES).forEach(([code, name]) => {
        if (name.toLowerCase().includes(searchTerm) && 
            !results.find(r => r.code === code)) {
            results.push({ code, name, type: 'name' });
        }
    });
    
    return results.slice(0, 10); // Limit to 10 results
};

export const getStationName = (code) => {
    return STATION_CODES[code.toUpperCase()] || code;
};

export const getStationCode = (name) => {
    const entry = Object.entries(STATION_CODES).find(([code, stationName]) => 
        stationName.toLowerCase() === name.toLowerCase()
    );
    return entry ? entry[0] : name;
};